---
- name: Update apt
  apt: update_cache=yes
  sudo: yes

- name: Install base packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - git-core
    - build-essential
    - fontconfig # needed for phantomjs
    - nodejs
    - curl
    - python-psycopg2
    - postgresql
    - postgresql-client
    - libpq-dev
    - postgresql-contrib
    - nfs-common # make virtualbox faster
    - imagemagick
    - fail2ban
    - unattended-upgrades

- name: copy up .bashrc
  copy: dest=~/.bashrc
        src=bashrc

- name: copy up .bash_profile
  copy: dest=~/.bash_profile
        src=bash_profile
